test gpt review
freeverseio/laos pull request #104
Opened 2023-10-24 10:41 UTC by ccubu

2023-10-24 10:55 UTC, asiniscalchi commented on .github/workflows/chatgpt.yml
> +
the black lines should be removed

2023-10-24 10:57 UTC, asiniscalchi requested changes

2023-10-24 10:57 UTC, asiniscalchi commented on .github/workflows/chatgpt.yml
> +
please handle it

2023-10-24 11:19 UTC, ccubu commented on .github/workflows/chatgpt.yml
> +
The purpose of this pr was to highlight the chat gpt reviews, I don't intend to merge it

2023-10-25 14:57 UTC, dastanfv commented
gpt review

2023-10-25 14:59 UTC, dastanfv commented
[gpt review]

2023-10-25 15:57 UTC, closed without merging