Feature evolve assets
freeverseio/laos pull request #125
Opened 2023-10-27 08:23 UTC by magecnion

2023-10-27 09:23 UTC, magecnion commented
/review

2023-10-27 09:30 UTC, magecnion commented
/describe

2023-10-27 09:44 UTC, asiniscalchi requested changes

2023-10-27 09:44 UTC, asiniscalchi commented on ownership-chain/precompile/laos-evolution/contracts/LaosEvolution.sol
> +    event MetadataUpdate(
Token metadata needs to be part of the event otherwise otherwise it will be possible retrive it only by archive nodes.

2023-10-27 10:39 UTC, magecnion commented
/review -i

2023-10-27 12:43 UTC, tonimateos requested changes

2023-10-27 12:59 UTC, magecnion commented on ownership-chain/precompile/laos-evolution/contracts/LaosEvolution.sol
> +    function evolveWithExternalUri(
I will change in a following PR

2023-10-27 13:02 UTC, tonimateos requested changes

2023-10-27 13:02 UTC, tonimateos commented on ownership-chain/precompile/laos-evolution/contracts/LaosEvolution.sol
> +    /// @param tokenId the id for which the metadata has changed
sorry missing one word: "the id OF THE TOKEN for which..."

2023-10-27 14:05 UTC, tonimateos requested changes

2023-10-27 14:05 UTC, tonimateos commented on ownership-chain/precompile/laos-evolution/contracts/LaosEvolution.sol
> +        uint256 tokenId,
please make the tokenId param indexed

2023-10-30 13:47 UTC, tonimateos approved these changes

2023-10-30 15:23 UTC, asiniscalchi requested changes

2023-10-30 15:23 UTC, asiniscalchi commented on ownership-chain/precompile/laos-evolution/src/tests.rs
> +			.write(token_uri.clone())
here it's better to use `Bytes` to pack the data

2023-10-31 08:02 UTC, asiniscalchi approved these changes

2023-10-31 08:52 UTC, asiniscalchi approved these changes

2023-10-31 08:52 UTC, merged