Add astar specs and zombienet config
freeverseio/laos pull request #139
Opened 2023-11-03 16:28 UTC by dastanfv

2023-11-05 14:03 UTC, dastansam commented
/describe

2023-11-05 14:03 UTC, dastanfv commented
/describe

2023-11-05 14:03 UTC, dastanfv commented
/review

2023-11-06 08:45 UTC, dastanfv commented on ownership-chain/zombienet/native.toml
> +max_capacity = 8
```bash
`max_capacity` - specifies how many messages can be in the channel at once.
`max_message_size` - specifies the maximum size of the messages.
```

2023-11-06 08:53 UTC, asiniscalchi requested changes

2023-11-06 08:53 UTC, asiniscalchi commented on ownership-chain/zombienet/native.toml
> +  name = "Alice"
let's use simply "astar"

2023-11-06 08:53 UTC, asiniscalchi commented on ownership-chain/zombienet/native.toml
>    name = "Alice"
let's use "ownership" or something better than Alice if possible:
![image](https://github.com/freeverseio/laos/assets/2387339/31500987-cedd-41a6-9fe8-97296090df12)

2023-11-06 09:54 UTC, asiniscalchi approved these changes

2023-11-06 09:54 UTC, merged