Apply SBP review
freeverseio/laos pull request #166
Opened 2023-11-10 08:52 UTC by dastanfv

2023-11-10 08:53 UTC, dastanfv commented
/review

2023-11-10 08:59 UTC, dastanfv commented on ownership-chain/primitives/src/lib.rs
> +	Weight::from_parts(WEIGHT_REF_TIME_PER_SECOND.saturating_div(2), 5 * 1024 * 1024);
```
pub BlockGasLimit: U256 = U256::from(NORMAL_DISPATCH_RATIO * MAXIMUM_BLOCK_WEIGHT.ref_time() / WEIGHT_PER_GAS);
```

2023-11-10 14:18 UTC, asiniscalchi commented
/improve better name for the test

2023-11-10 14:19 UTC, asiniscalchi commented
/ask what about a better name for the test ?

2023-11-10 14:29 UTC, asiniscalchi requested changes
test to check txpool is working missing

2023-11-13 09:15 UTC, magecnion commented on ownership-chain/e2e-tests/tests/test_txpool.ts
> +describeWithExistingNode("Frontier RPC (TxPoolApi)", (context) => {
txpool tests are not idempotent, is there any way to change this so we don't have to reset zombienet everytime we run test?

2023-11-13 09:17 UTC, magecnion requested changes

2023-11-13 09:17 UTC, magecnion commented on ownership-chain/e2e-tests/tests/test_txpool.ts
> +describeWithExistingNode("Frontier RPC (TxPoolApi)", (context) => {
txpool tests are not idempotent, is there any way to modify this so that we don't have to reset zombienet everytime we run a test?

2023-11-13 10:48 UTC, magecnion approved these changes

2023-11-13 12:12 UTC, asiniscalchi approved these changes

2023-11-13 12:12 UTC, merged