Update Project Metadata and Naming in Node
freeverseio/laos pull request #190
Opened 2023-11-20 16:30 UTC by asiniscalchi

## PR Type:
Refactoring

___
## PR Description:
This PR includes changes to update the project metadata and naming in the node. The main changes include:
- Renaming from "Frontier Parachain Collator Template" to "LAOS Parachain Node"
- Updating the support URL to point to the new project repository
- Changing the copyright start year from 2020 to 2023
- Updating the project metadata in the Cargo.toml file

___
## PR Main Files Walkthrough:
<details> <summary>files:</summary>

- `ownership-chain/node/src/command.rs`: Updated the implementation name, description, support URL, and copyright start year for both Cli and RelayChainCli.
- `ownership-chain/node/Cargo.toml`: Updated the project metadata including the homepage and repository URLs.
</details>

2023-11-20 16:30 UTC, asiniscalchi commented
/describe

2023-11-20 16:40 UTC, asiniscalchi commented
/description

2023-11-20 17:07 UTC, magecnion requested changes

2023-11-20 17:07 UTC, magecnion commented on ownership-chain/node/Cargo.toml
> +authors = { workspace = true }
maybe a typo?

2023-11-20 17:08 UTC, magecnion requested changes

2023-11-20 17:08 UTC, magecnion commented on ownership-chain/node/Cargo.toml
>  edition = "2021"
2023?

2023-11-20 17:20 UTC, asiniscalchi commented on ownership-chain/node/Cargo.toml
>  edition = "2021"
it's the edition of rust

2023-11-20 17:20 UTC, asiniscalchi commented on ownership-chain/node/Cargo.toml
> +authors = { workspace = true }
no no it's correct by "Freeverse"
``` 
2023-11-20 18:20:12 LAOS Parachain Node    
2023-11-20 18:20:12 ✌️  version 0.1.0-126c9b47bcf    
2023-11-20 18:20:12 ❤️  by Freeverse, 2023-2023    
2023-11-20 18:20:12 📋 Chain specification: klaos network    
2023-11-20 18:20:12 🏷  Node name: recondite-tongue-0177    
```

2023-11-20 17:35 UTC, magecnion submitted a review, later dismissed

2023-11-21 08:37 UTC, dastanfv commented on ownership-chain/node/src/command.rs
>  		{} <parachain-args> -- <relay-chain-args>",
line 109 still has `parachain-template` link

2023-11-21 10:09 UTC, asiniscalchi commented on ownership-chain/node/src/command.rs
>  		{} <parachain-args> -- <relay-chain-args>",
fixed

2023-11-21 10:16 UTC, dastanfv approved these changes

2023-11-21 10:28 UTC, merged