Addition of New Bootnode to Giedi Chain Configuration
freeverseio/laos pull request #274
Opened 2024-01-05 15:35 UTC by asiniscalchi

## Type
enhancement

___

## Description
- Added a new bootnode to the `giedi_chain` configuration in the `ownership-chain/specs/giedi.raw.json` file.

___

## Changes walkthrough
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>giedi.raw.json&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        ownership-chain/specs/giedi.raw.json<br><br>

**A new bootnode has been added to the `giedi_chain` <br>configuration.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/freeverseio/laos/pull/274/files#diff-f171d4bbbe944f3663ec5b14ea75cb37e42a60453948d7aac948c9d79c0f500e"> +1/-0</a></td>

</tr>                    
</table></td></tr></tr></tbody></table>

2024-01-05 15:35 UTC, asiniscalchi commented
/describe

2024-01-05 15:46 UTC, magecnion approved these changes

2024-01-05 16:00 UTC, magecnion requested changes
test failing

2024-01-08 09:25 UTC, magecnion approved these changes

2024-01-08 10:25 UTC, ccubu approved these changes

2024-01-08 10:26 UTC, merged