pallet_vesting integrated
freeverseio/laos pull request #295
Opened 2024-01-18 14:44 UTC by asiniscalchi

2024-01-18 16:02 UTC, asiniscalchi commented
/describe

2024-01-19 09:47 UTC, dastanfv submitted a review, later dismissed

2024-01-22 11:05 UTC, asiniscalchi commented
/describe

2024-01-22 11:12 UTC, dastanfv commented on ownership-chain/runtime/src/tests/constant_tests.rs
> +		let vesting_duration = 24 * 4; // 4 times the cliff duration
```suggestion
		let vesting_duration = cliff_duration * 4; // 4 times the cliff duration
```

2024-01-22 11:12 UTC, dastanfv commented on ownership-chain/runtime/src/tests/constant_tests.rs
> +		let per_block = UNIT; // Amount vested per block
```suggestion
		let amount_per_block = UNIT; // Amount vested per block
```

2024-01-22 16:25 UTC, dastanfv submitted a review, later dismissed

2024-01-23 09:14 UTC, magecnion requested changes

2024-01-23 11:24 UTC, asiniscalchi commented on ownership-chain/runtime/src/tests/constant_tests.rs
> +		for block_num in cliff_duration..=cliff_duration + vesting_duration as u32 {
first step of the loop check that

2024-01-23 11:24 UTC, asiniscalchi commented on ownership-chain/runtime/src/tests/constant_tests.rs
> +			assert_eq!(Balances::total_balance(&bob), total_vested_amount);
I agree is a superfluous check

2024-01-23 11:26 UTC, asiniscalchi commented on ownership-chain/runtime/src/tests/constant_tests.rs
> +		let alice = AccountId::from_str(ALICE).unwrap();
don't think it is needed. I am checking the functionality here.

2024-01-23 11:38 UTC, asiniscalchi commented on ownership-chain/runtime/src/tests/constant_tests.rs
https://github.com/freeverseio/laos/pull/298 <--- this PR moves the tests into mod.rs

2024-01-23 15:08 UTC, dastanfv commented
just saw that the file of the tests is called `constant_tests.rs`. I agree with @magecnion that it should be renamed, possibly to `vesting_tests.rs` or sth like that.

2024-01-23 15:43 UTC, magecnion approved these changes

2024-01-23 15:46 UTC, magecnion approved these changes

2024-01-23 16:07 UTC, dastanfv approved these changes

2024-01-23 16:09 UTC, merged