Feature/add public minting to precompiles
freeverseio/laos pull request #299
Opened 2024-01-19 11:27 UTC by magecnion

2024-01-19 11:27 UTC, magecnion commented
/describe

2024-01-22 08:44 UTC, tonimateos requested changes

2024-01-22 08:44 UTC, tonimateos commented on ownership-chain/precompile/evolution-collection/contracts/EvolutionCollection.sol
> +    /// @notice Enables public minting for the collection
explain below: 
// When enabled, any address is allowed to mint on this collection
// This does not affect evolution: only the owner of the collection can continue evolving assets

2024-01-22 08:56 UTC, asiniscalchi submitted a review, later dismissed

2024-01-22 09:27 UTC, dastanfv commented on ownership-chain/precompile/evolution-collection/src/lib.rs
> +				Ok(succeed(sp_std::vec![]))
should this be with `EvmDataWriter` to be more consistent?

2024-01-22 09:27 UTC, dastanfv commented on ownership-chain/precompile/evolution-collection/src/lib.rs
> +				Ok(succeed(sp_std::vec![]))
`EvmDataWriter` instead

2024-01-22 15:17 UTC, tonimateos approved these changes

2024-01-22 15:29 UTC, merged