added storage version
freeverseio/laos pull request #319
Opened 2024-01-29 15:05 UTC by asiniscalchi

2024-01-29 15:05 UTC, asiniscalchi commented
/describe

2024-02-02 10:07 UTC, dastanfv requested changes

2024-02-02 10:07 UTC, dastanfv commented on ownership-chain/runtime/src/migration.rs
> +		consumed_weight += db_weight.writes(1);
this is two writes: `AccountCodes` and `AccountMetadata`. And also does two reads

2024-02-02 10:07 UTC, dastanfv commented on ownership-chain/runtime/src/migration.rs
> +		let asset_metadata_extender_address: H160 = H160::from_low_u64_be(1029);
could probably use `hash` function from the `precompile-utils`, to be more consistent

2024-02-02 10:07 UTC, dastanfv commented on ownership-chain/runtime/src/migration.rs
> +pub struct AddPrecompileBytecode<T>(sp_std::marker::PhantomData<T>);
some comment would be nice

2024-02-02 10:07 UTC, dastanfv commented on ownership-chain/runtime/src/migration.rs
> +pub struct AddPrecompileBytecode<T>(sp_std::marker::PhantomData<T>);
Also, maybe name it `InjectDamePrecompileBytecode` or something more concrete?

2024-02-02 10:07 UTC, dastanfv commented on ownership-chain/runtime/src/migration.rs
> +		consumed_weight += db_weight.writes(1);
see in `EvolutionCollectionFactory::create_collection()`, we manually record the weight for this there as well

2024-02-02 13:35 UTC, dastanfv commented on ownership-chain/runtime/src/migration.rs
> +use frame_support::{
is this duplicate of `./precompiles/migration.rs`?

2024-02-02 13:35 UTC, dastanfv commented on ownership-chain/runtime/src/precompiles/mod.rs
> +pub fn hash(a: u64) -> H160 {
small nit here:
```suggestion
pub(crate) fn hash(a: u64) -> H160 {
```

2024-02-02 14:49 UTC, dastanfv approved these changes

2024-02-05 07:39 UTC, magecnion approved these changes

2024-02-05 09:28 UTC, merged