Add tests for `ParachainStakingAdapter`
freeverseio/laos pull request #417
Opened 2024-03-06 16:32 UTC by dastanfv

2024-03-07 13:46 UTC, asiniscalchi requested changes

2024-03-07 13:46 UTC, asiniscalchi commented on ownership-chain/runtime/laos/src/configs/parachain_staking.rs
> +			// Roll to the first block of the next session.
first block?

2024-03-07 14:46 UTC, asiniscalchi submitted a review, later dismissed

2024-03-08 09:48 UTC, magecnion commented on ownership-chain/utils/test/src/lib.rs
> +/// Rolls to a block number by simulating the block production
missing example comment?

2024-03-08 11:10 UTC, magecnion approved these changes

2024-03-08 11:23 UTC, magecnion approved these changes

2024-03-08 12:21 UTC, asiniscalchi approved these changes

2024-03-08 12:22 UTC, merged