Fail clippy on warnings, try remove TODO comments
freeverseio/laos pull request #547
Opened 2024-04-08 08:49 UTC by dastanfv

2024-04-08 08:51 UTC, dastanfv commented on pallets/parachain-staking/src/delegation_requests.rs
> +		let new_amount: BalanceOf<T> = bonded_amount.saturating_sub(decrease_amount);
this is kinda big deal, I am wondering if there are more instances of using unsafe arithmetic in the staking code

2024-04-08 08:52 UTC, dastanfv commented on pallets/parachain-staking/src/mock.rs
> +#[allow(unused_imports)]
this is very weird compiler error, maybe because `block_author` is used only in tests it always complains that it is unused

2024-04-08 09:20 UTC, asiniscalchi commented
that's cool

2024-04-08 11:20 UTC, asiniscalchi requested changes

2024-04-08 11:20 UTC, asiniscalchi commented on node/src/eth.rs
> +#[allow(clippy::too_many_arguments)]
sure, could you put a TODO

2024-04-09 10:37 UTC, asiniscalchi approved these changes

2024-04-09 11:07 UTC, merged