Feature/add democracy pallet
freeverseio/laos pull request #759
Opened 2024-09-04 13:00 UTC by asiniscalchi

2024-09-04 13:47 UTC, asiniscalchi commented
/describe

2024-09-05 10:08 UTC, magecnion commented on runtime/laos/src/configs/democracy.rs
> +		pallet_collective::EnsureProportionAtLeast<AccountId, CouncilCollective, 1, 2>;
comment above says _simple-majority_ whereas `pallet_collective::EnsureProportionAtLeast<AccountId, CouncilCollective, 1, 2>` is `HalfOfCouncil`

2024-09-05 10:09 UTC, magecnion commented on runtime/laos/src/configs/democracy.rs
> +	type ExternalOrigin = HalfOfCouncil;
same as above

2024-09-05 11:12 UTC, magecnion approved these changes

2024-09-05 13:46 UTC, luispdm requested changes

2024-09-05 13:46 UTC, luispdm commented on runtime/laos/Cargo.toml
> +	"pallet-democracy/std",
Not related to this line but the requested modification affects this file. We should replace
```toml
fast-mode=[]
```
for:
```toml
fast-runtime=[]
```
This is what `prod_or_fast` does: https://github.com/paritytech/polkadot-sdk/blob/a947cb831d8d56228e7aa84355410c50864a816e/polkadot/runtime/common/src/lib.rs#L272

2024-09-05 13:49 UTC, magecnion approved these changes

2024-09-05 13:53 UTC, luispdm approved these changes

2024-09-05 13:53 UTC, merged