Evochain: Owner of collection
freeverseio/laos pull request #80
Opened 2023-10-18 11:45 UTC by dastanfv

2023-10-18 12:19 UTC, tonimateos requested changes

2023-10-18 12:19 UTC, tonimateos commented on evolution-chain/precompile/laos-evolution/contracts/LaosEvolution.sol
> +    /// @return owner the owner of the collection
If the return of the method does not have an owner, then you don't need to use it in the @return.
In this case, you should use
/// @return the owner of the collection

instead, if you had this: function ownerOfCollection(collectionId) returns (address admin);

you would have to use:
/// @return admin the owner of the collection

2023-10-18 12:19 UTC, tonimateos commented on evolution-chain/precompile/laos-evolution/contracts/LaosEvolution.sol
> +    /// @return owner the owner of the collection
And indeed, the same applies to line 17, you should just use 

    /// @return the id of the newly created collection

2023-10-18 14:07 UTC, tonimateos approved these changes

2023-10-19 08:27 UTC, dastanfv commented on evolution-chain/precompile/laos-evolution/src/lib.rs
> +pub const SELECTOR_LOG_CREATE_COLLECTION: [u8; 32] = keccak256!("CreateCollection(uint64,address)");
`NewCollection` seems to be more aligned with the Solidity conventions, so I chose that

2023-10-19 08:54 UTC, asiniscalchi approved these changes

2023-10-19 08:55 UTC, merged

2023-10-19 10:01 UTC, tonimateos commented on evolution-chain/precompile/laos-evolution/src/lib.rs
> +pub const SELECTOR_LOG_CREATE_COLLECTION: [u8; 32] = keccak256!("CreateCollection(uint64,address)");
Although I don't see explicit naming recommendations in Solidity, my experience is that normally "New" is used. I have collected some examples:

From [1]:

    // Logged when the owner of a node assigns a new owner to a subnode.
    event NewOwner(bytes32 indexed node, bytes32 indexed label, address owner);

    // Logged when the resolver for a node changes.
    event NewResolver(bytes32 indexed node, address resolver);

    // Logged when the TTL of a node changes
    event NewTTL(bytes32 indexed node, uint64 ttl);

From [2]: event NewMint


[1] https://github.com/ensdomains/ens/blob/master/contracts/ENS.sol
[2] https://basescan.org/token/0xd2b2a5d79cab06e0efc40b6c80a152a6480011a6#code