Feature/zombienet asset hub has to be 1000
freeverseio/laos pull request #818
Opened 2024-10-15 12:30 UTC by asiniscalchi

2024-10-15 12:37 UTC, asiniscalchi commented
/describe

2024-10-16 07:05 UTC, asiniscalchi commented
/describe

2024-10-16 10:59 UTC, magecnion approved these changes

2024-10-16 13:23 UTC, luispdm requested changes

2024-10-16 13:23 UTC, luispdm commented on zombienet/xcm-native.toml
> -[settings]
Why have you merged `native`and `xcm-native` into one single file? If i don't need to test XCM features, I prefer spawning a local environment without AssetHub Rococo.

If you plan on keeping one single `.toml`, I suggest editing the [README](https://github.com/freeverseio/laos/blob/main/zombienet/README.md)

2024-11-12 11:36 UTC, closed without merging