Feature/evm tocken uri
freeverseio/laos pull request #88
Opened 2023-10-20 10:04 UTC by asiniscalchi

2023-10-23 14:15 UTC, tonimateos submitted a review, later dismissed

2023-10-24 08:16 UTC, magecnion requested changes

2023-10-24 08:16 UTC, magecnion commented on evolution-chain/precompile/laos-evolution/src/tests.rs
> +	/// The mock type is named `Mock`, and the implementation uses the provided ehttps://meet.google.com/ntw-cgcg-fjfxpressions.
copy-paste error?

2023-10-24 08:47 UTC, magecnion approved these changes

2023-10-24 08:47 UTC, merged