Refactor e2e tests to increase its determinism and scalability
freeverseio/laos pull request #894
Opened 2024-11-26 09:29 UTC by tsenovilla

This PR aims to improve e2e test, making them not dependent on timeouts and improving its scalability and maintenance

2024-11-29 14:22 UTC, asiniscalchi submitted a review, later dismissed

2024-12-02 09:51 UTC, magecnion commented
I think there is a bit of redundancy in the folder names. Some examples are:
- e2e-tests
- e2e-tests/chopsticks-tests
- e2e-tests/chopsticks-tests/test-teleport-laos.ts
- e2e-tests/zombienet-tests
- e2e-tests/chopsticks-tests/test-staking.ts

One idea could be to create a `suites` folder that stores both `zombienet` and `chopsticks`, where we also place all the related files for each tool, regardless of whether they are tests or not. For example:
```
suites/
  chopsticks
    configs/
    tests/
  zombienet/
    native.toml
    tests/
```

2024-12-02 09:53 UTC, magecnion requested changes

2024-12-02 09:53 UTC, magecnion commented on e2e-tests/chopsticks-configs/laos.yml
> +endpoint: wss://rpc.laosvenus.gorengine.com
What if we use the Laos local network instead, as we did previously? AFAIK, I think there is no need to start from the Venus network.

2024-12-02 11:08 UTC, luispdm approved these changes

2024-12-02 11:40 UTC, magecnion approved these changes

2024-12-02 11:41 UTC, merged