Test e2e runtime upgrade
freeverseio/laos pull request #909
Opened 2024-12-11 09:39 UTC by tsenovilla

Add a e2e test using chopsticks to test the runtime upgrade

2024-12-11 14:17 UTC, asiniscalchi submitted a review, later dismissed

2024-12-11 15:10 UTC, luispdm requested changes

2024-12-11 15:22 UTC, tsenovilla commented on e2e-tests/utils/setups.ts
> +	providerAssetHubNodeIP?: string
solved with last commit

2024-12-11 15:25 UTC, luispdm approved these changes

2024-12-12 09:50 UTC, asiniscalchi approved these changes

2024-12-12 09:50 UTC, merged